[package]
name = "qr"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bitvec = "^0.22.3"
encoding_rs = "^0.8.28"
ndarray = { version = "^0.15.3", features = ["rayon"] }
rayon = "^1.5.1"