[package]
name = "qrcli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qr = { path = '../qr', features = ["image"] }
clap = "^2.33"
