[package]
name = "qrcli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qr = { path = '../qr', features = ["image", "serde"] }
ndarray = "^0.15"
image = "^0.23"
serde_json = "^1.0"